{"uid":"68135242f92ef5ed","name":"test_run_failure_check_raises","fullName":"test.utilities.test_shell.TestRunFunction#test_run_failure_check_raises","historyId":"861ab8b44740520bfda663d2e89bd90d","time":{"start":1757125648880,"stop":1757125648882,"duration":2},"description":"Verify a failing command with check=True raises CalledProcessError.","descriptionHtml":"<p>Verify a failing command with check=True raises CalledProcessError.</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"test.utilities"},{"name":"suite","value":"test_shell"},{"name":"subSuite","value":"TestRunFunction"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"2202-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.utilities.test_shell"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":[]},"source":"68135242f92ef5ed.json","parameterValues":[]}