{"name": "test_error_without_traceback", "status": "passed", "description": "Verify error() logs at the ERROR level without a traceback.", "start": 1756776652916, "stop": 1756776652918, "uuid": "0169461c-c403-441d-8f07-95187acf3166", "historyId": "3046a012cff151115e61e02786daf834", "testCaseId": "3046a012cff151115e61e02786daf834", "fullName": "test.utilities.test_cli.TestAlertFunctions#test_error_without_traceback", "labels": [{"name": "parentSuite", "value": "test.utilities"}, {"name": "suite", "value": "test_cli"}, {"name": "subSuite", "value": "TestAlertFunctions"}, {"name": "host", "value": "dtc205659"}, {"name": "thread", "value": "543787-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.utilities.test_cli"}], "titlePath": ["test", "utilities", "test_cli.py", "TestAlertFunctions"]}
