{"name": "test_error_without_traceback", "status": "passed", "description": "Verify error() logs at the ERROR level without a traceback.", "start": 1756775768735, "stop": 1756775768736, "uuid": "eefd0b1e-b2dd-4a53-80d6-e2cb76c2d81a", "historyId": "3046a012cff151115e61e02786daf834", "testCaseId": "3046a012cff151115e61e02786daf834", "fullName": "test.utilities.test_cli.TestAlertFunctions#test_error_without_traceback", "labels": [{"name": "parentSuite", "value": "test.utilities"}, {"name": "suite", "value": "test_cli"}, {"name": "subSuite", "value": "TestAlertFunctions"}, {"name": "host", "value": "dtc205659"}, {"name": "thread", "value": "529406-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.utilities.test_cli"}], "titlePath": ["test", "utilities", "test_cli.py", "TestAlertFunctions"]}
