{"name": "test_error_without_traceback", "status": "passed", "description": "Verify error() logs at the ERROR level without a traceback.", "start": 1756776101358, "stop": 1756776101361, "uuid": "b7d06fd5-b3e0-4cea-b8ff-7829c4804a20", "historyId": "3046a012cff151115e61e02786daf834", "testCaseId": "3046a012cff151115e61e02786daf834", "fullName": "test.utilities.test_cli.TestAlertFunctions#test_error_without_traceback", "labels": [{"name": "parentSuite", "value": "test.utilities"}, {"name": "suite", "value": "test_cli"}, {"name": "subSuite", "value": "TestAlertFunctions"}, {"name": "host", "value": "dtc205659"}, {"name": "thread", "value": "534552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.utilities.test_cli"}], "titlePath": ["test", "utilities", "test_cli.py", "TestAlertFunctions"]}
